Simplified it
	modified:   run_script.conf
	modified:   run_script.sh
	modified:   run_script_functions

diff --git a/run_script_functions b/run_script_functions
--- a/run_script_functions
+++ b/run_script_functions
@@ -3,82 +3,62 @@
 #    Functions for run_script.sh
 
 #
-# Check if this program is already running and if so, exit.
+# cleanup on failures
 #
+trap 'cleanup' 1 2 3 6 9 15   ### Trap these signals in order to do cleanup
 
+cleanup() {
+  release_lock
+  exit 255              ### Indicate interrupted or killed
+}
+
+#
+# Log format
+#
+display_w_timestamp() {
+  disptime="`date +'%Y-%m-%d %H:%M:%S'`"
+
+  echo "$disptime $1"
+
+}
+
+#
+# test and/or create a lock file
+#
 ck_n_put_lock() {
 
   if [ -n "$LOCK" ] ; then
     return
   fi
 
-  PROC2LOCK=$1  ### process to lock
-  CKTIME=$2     ### wait for lock to be released. (unused)
-  pscount=0
-  LOCKFILE=$APPHOME/locks/LCK..$PROC2LOCK   ### lock file name
+  if [ ! -d "$APPDIR/locks" ] ; then
+    mkdir $APPDIR/locks
+  fi
+
+  LOCKFILE=$APPDIR/locks/LCK..$APPNAME   ### lock file name
 
   runpid=`cat $LOCKFILE 2> /dev/null`      ### Get process ID
   if [ -n "$runpid" ] ; then               
     psrunpid=`ps -p$runpid | grep $runpid` ### Is it really running?
     if [ -n "$psrunpid" ] ; then
+      display_w_timestamp "Lock file exists: $psrunpid "
       exit 0
     fi
-    if [ ! -z "$CKTIME" ] ; then          ### (unused)
-      if [ $CKTIME = "YES" ] ; then
-        ISTHISOLD=`$APPBIN/lock_too_old.pl $LOCKFILE`
-        echo "IS THIS OLD = $ISTHISOLD\n"
-        if [ $ISTHISOLD = "TRUE" ] ; then    ### Is it over five minutes old?
-          psrunpid2=`ps -few|grep $runpid | grep raw` ### Is raw running?
-          if [ -n "$psrunpid2" ] ; then
-            kill -9 $psrunpid2  ### Kill raw.pl
-          fi
-          kill -9 $psrunpid   ### Kill linger_ld_credit.sh
-        fi
-      fi
-    fi
   fi
-  #  echo "$$" > $LOCKFILE
+  echo "$$" > $LOCKFILE  ### Create a new lock file
 }
 
 
 #
 # Remove the lock.
 #
-
 release_lock() {
   if [ -n "$LOCK" ] ; then
     return
   fi
 
-  PROC2LOCK=$1
-  LOCKFILE=$APPHOME/locks/LCK..$PROC2LOCK
+  LOCKFILE=$APPDIR/locks/LCK..$APPNAME
   rm $LOCKFILE          ### remove lock file
-}
-
-
-#
-# Initialize a directory
-#
-
-do_initialize() {
-
-  INIT_DIR="$1"
-
-  if [ ! -d "$INIT_DIR" ] ; then
-    echo "Directory $INIT_DIR must exist in order to initialize.\n"
-  else 
-    cd $INIT_DIR
-    DIRLIST="conf locks logs"
-    for i in `echo $DIRLIST`; do
-      if [ ! -d $i ] ; then
-        echo "Creating $i"
-        mkdir $i
-      else 
-        echo "Directory $i already exists\n"
-      fi
-    done
-  fi
-
 }
 
 
@@ -88,33 +68,15 @@ do_initialize() {
 
 do_run_script() {
 
-  LOCKNAME="$1"
-  shift
-  SCRIPTNAME="$1"
-  shift
-  ARGS=$@
+  ck_n_put_lock
 
-  cd $APPBIN
-  ck_n_put_lock $LOCKNAME
-
-  if [ -n "$NOTEE" ] ; then
-
-    if [ -n "$DEBUG" ] ; then
-      sh -x $APPBIN/$SCRIPTNAME $ARGS 
-    else
-      $APPBIN/$SCRIPTNAME $ARGS 
-    fi
-
-#  else 
-#
-#    if [ -n "$DEBUG" ] ; then
-#      sh -x $APPBIN/$SCRIPTNAME $ARGS |tee -a $APPLOG
-#    else
-#      $APPBIN/$SCRIPTNAME $ARGS |tee -a $APPLOG
-#    fi
-
+  if [ -n "$DEBUG" ] ; then
+    sh -x $EXEC
+  else
+    $EXEC
   fi
-  release_lock $LOCKNAME
+
+  release_lock 
 }
 
 
